# Laboratorio 4. Regresion lineal

> **Antes de comenzar**
>
> Este laboratorio está diseñado para ejecutarse en **Google Colab**.
>
> Una vez abierto en Google Colab, ejecute la primera celda para clonar el repositorio del curso y acceder a los conjuntos de datos utilizados en este laboratorio.

In [ ]:
!git clone https://github.com/urendacdenisse-hub/modelado-de-datos.git

In [ ]:
%cd modelado-de-datos

# Diagnóstico de los supuestos de regresión lineal

En esta lección analizaremos distintos conjuntos de datos ficticios diseñados para explorar los supuestos de la regresión lineal.

Comenzaremos con un escenario donde los supuestos se cumplen razonablemente bien y, posteriormente, analizaremos casos donde algunos de ellos son violados.

## Regresión lineal simple

### Dataset

`01_relaciones_mixtas`

### Variables

- **Predictora:** `horas_estudio`
- **Respuesta:** `puntaje_examen`

### ¿Qué debemos esperar?

El puntaje del examen tiene una relación lineal positiva con las horas de estudio.

Esperamos observar:

- una relación aproximadamente lineal;
- residuos aproximadamente normales;
- varianza aproximadamente constante de los residuos;
- observaciones independientes.

In [8]:
import pandas as pd

ruta = "../../datos/datasets_regresion_lineal.xlsx"

df = pd.read_excel(ruta, sheet_name="01_relaciones_mixtas" )
df = df[["horas_estudio", "puntaje_examen"]]
df.head()

   horas_estudio  puntaje_examen
0           3.48           60.03
1           7.15           85.69
2           6.66           74.59
3           9.36          100.27
4           2.24           64.57

## Regresión lineal múltiple

### Dataset

`02_supuestos_ok`

### Variables

- **Predictoras:** `superficie_m2`, `antiguedad_anios`, `distancia_centro_km`, `indice_calidad_1_10`
- **Respuesta:** `precio_vivienda_miles`

### ¿Qué debemos esperar?

En este conjunto de datos, el precio de una vivienda depende linealmente de múltiples características.

Esperamos observar:

- una relación lineal entre los predictores y la respuesta;
- residuos aproximadamente normales;
- varianza aproximadamente constante;
- ausencia de multicolinealidad fuerte;
- observaciones independientes.

In [ ]:
df = pd.read_excel(ruta, sheet_name="02_supuestos_ok")
df.head()

,superficie_m2,antiguedad_anios,distancia_centro_km,indice_calidad_1_10,precio_vivienda_miles
0,172.14,17.73,16.57,8.58,363.55
1,100.34,30.24,22.60,4.64,175.65
2,146.63,18.20,6.14,5.87,304.16
3,113.85,37.88,24.57,7.32,180.81
4,222.88,32.62,22.12,5.72,332.82

# Cuando los supuestos no se cumplen

Hasta ahora hemos trabajado con datos que se comportan de acuerdo con los supuestos del modelo lineal.

Ahora analizaremos qué ocurre cuando estos supuestos comienzan a fallar.

## No normalidad de los residuos

### Dataset

`03_no_normalidad`

### Variables

- **Predictoras:** `superficie_m2`, `antiguedad_anios`, `distancia_centro_km`, `indice_calidad_1_10`
- **Respuesta:** `precio_vivienda_miles`

### ¿Qué debemos esperar?

- La estructura del modelo continúa siendo lineal, pero los errores no siguen una distribución normal.

- Esperamos observar desviaciones de la normalidad al analizar los residuos del modelo.

In [3]:
df = pd.read_excel(ruta, sheet_name="03_no_normalidad")
df.head()

,superficie_m2,antiguedad_anios,distancia_centro_km,indice_calidad_1_10,precio_vivienda_miles
0,143.39,14.02,4.44,8.92,325.76
1,165.01,15.22,15.80,9.60,332.07
2,160.71,4.67,3.34,4.61,305.25
3,174.31,44.25,3.45,9.05,335.15
4,191.32,18.92,15.71,9.51,370.59

## Heteroscedasticidad

### Dataset

`04_heteroscedasticidad`

### Variables

- **Predictoras:** `ingreso_mensual_miles`, `tamano_hogar`, `edad_jefe_hogar`
- **Respuesta:** `gasto_mensual_miles`

### ¿Qué debemos esperar?

- La relación entre los predictores y la respuesta continúa siendo aproximadamente lineal, pero la variabilidad de los errores no es constante.

- En particular, esperamos que la dispersión aumente conforme aumenta el nivel de ingreso.

In [4]:
df = pd.read_excel(ruta, sheet_name="04_heteroscedasticidad")
df.head()

   ingreso_mensual_miles  tamano_hogar  edad_jefe_hogar  gasto_mensual_miles
0                  21.56             5            26.24                25.99
1                  86.87             1            37.53                26.93
2                  46.66             2            55.22                34.88
3                  88.36             4            65.11                48.13
4                  34.63             2            67.91                23.07

## Dependencia en los residuos

### Dataset

`05_dependencia_residuos`

### Variables

- **Predictoras:** `temperatura_c`, `ocupacion_pct`
- **Respuesta:** `consumo_energia_kwh`
- **Variable temporal:** `dia`

### ¿Qué debemos esperar?

En este conjunto de datos, las observaciones corresponden a mediciones realizadas a lo largo del tiempo.

Aunque la relación entre los predictores y la respuesta es lineal, los errores de observaciones consecutivas están relacionados entre sí.

Esperamos observar:

- una relación aproximadamente lineal;
- residuos aproximadamente normales;
- varianza aproximadamente constante;
- dependencia entre residuos consecutivos;
- un patrón temporal en los residuos.

Este comportamiento se conoce como autocorrelación.

In [5]:
df = pd.read_excel(ruta, sheet_name="05_dependencia_residuos")
df.head()

   dia  temperatura_c  ocupacion_pct  consumo_energia_kwh
0    1          27.43          80.95                94.16
1    2          17.70          66.66                72.48
2    3          24.27          88.43                89.13
3    4          19.51          48.08                67.69
4    5          22.84          90.61                91.28

## Multicolinealidad

### Dataset

`05_multicolinealidad`

### Variables

- **Predictoras:** `superficie_total_m2`, `habitaciones`, `banos`, `area_habitable_m2`, `antiguedad_anios`
- **Respuesta:** `precio_vivienda_miles`

### ¿Qué debemos esperar?

Algunos predictores contienen información muy similar.

En particular, variables relacionadas con el tamaño de la vivienda presentan una fuerte asociación entre sí.

Esperamos encontrar:

- correlaciones altas entre algunos predictores;
- dificultad para separar sus efectos individuales;
- posibles problemas en la estimación e interpretación de los coeficientes.

In [6]:
df = pd.read_excel(ruta, sheet_name="06_multicolinealidad")
df.head()

,superficie_total_m2,habitaciones,banos,area_habitable_m2,antiguedad_anios,precio_vivienda_miles
0,92.21,4,2.18,85.47,29.75,210.29
1,219.48,7,2.88,191.64,5.23,409.16
2,100.81,4,2.19,93.70,39.04,205.08
3,210.31,7,3.38,192.39,7.58,431.73
4,55.08,3,1.59,47.60,46.47,109.83

## Cuando la relación no es lineal

### Dataset

`07_multiple_no_lineal`

### Variables

- **Predictoras:** `temperatura_exterior_c`, `ocupantes`, `superficie_m2`, `humedad_relativa_pct`
- **Respuesta:** `consumo_energia_kwh`

### ¿Qué debemos esperar?

En este conjunto de datos, no todas las relaciones entre los predictores y la respuesta son lineales.

Aunque un modelo de regresión lineal múltiple puede capturar parte de la variabilidad del consumo de energía, esperamos encontrar **estructura sistemática en los residuos**, indicando que existe información que el modelo no logró capturar.

In [15]:
df = pd.read_excel(ruta, sheet_name="07_multiple_no_lineal")
df.head()

,temperatura_exterior_c,ocupantes,superficie_m2,humedad_relativa_pct,consumo_energia_kwh
0,21.43,3,138.83,37.78,33.76
1,6.05,7,197.53,39.62,80.20
2,26.65,2,166.00,53.79,43.16
3,19.94,7,167.29,34.46,56.23
4,12.23,4,197.92,41.76,50.74